sudo: false
language: node_js
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '6'
script:
  - yarn start validate
after_success:
  - yarn start release
branches:
  only:
    - master
